test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: 	original-storm-277913
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: portfolio-young-dusk-33877
google_dev:
  service: GCS
  project: original-storm-277913
  credentials: <%= Rails.root.join("config/secrets/original-storm-277913-fcc8e4d99c67.json") %>
  bucket: portfolio-young-dusk-33877
